-- 迁移：将旧的 11 个市场阶段简化为 5 个大阶段
--
-- 旧阶段 -> 新阶段映射：
-- - INITIALIZATION -> INTENTION_GENERATION
-- - INTENTION_GENERATION -> INTENTION_GENERATION
-- - STRATEGY_GENERATION -> STRATEGY_GENERATION
-- - RENEWAL_PROCESSING -> RENEWAL_PROCESSING
-- - DEPARTURE_ANNOUNCEMENT -> FREE_MARKET
-- - INITIAL_BIDDING -> FREE_MARKET
-- - NEGOTIATION_ROUNDS -> FREE_MARKET
-- - LAST_CHANCE -> FREE_MARKET
-- - TRANSFER_ROUNDS -> TRANSFER_ROUNDS
-- - FINALIZATION -> COMPLETED
-- - COMPLETED -> COMPLETED

-- 更新 transfer_market_states 表中的 current_phase
UPDATE transfer_market_states
SET current_phase = CASE current_phase
    WHEN 'INITIALIZATION' THEN 'INTENTION_GENERATION'
    WHEN 'INTENTION_GENERATION' THEN 'INTENTION_GENERATION'
    WHEN 'STRATEGY_GENERATION' THEN 'STRATEGY_GENERATION'
    WHEN 'RENEWAL_PROCESSING' THEN 'RENEWAL_PROCESSING'
    WHEN 'DEPARTURE_ANNOUNCEMENT' THEN 'FREE_MARKET'
    WHEN 'INITIAL_BIDDING' THEN 'FREE_MARKET'
    WHEN 'NEGOTIATION_ROUNDS' THEN 'FREE_MARKET'
    WHEN 'LAST_CHANCE' THEN 'FREE_MARKET'
    WHEN 'TRANSFER_ROUNDS' THEN 'TRANSFER_ROUNDS'
    WHEN 'FINALIZATION' THEN 'COMPLETED'
    WHEN 'COMPLETED' THEN 'COMPLETED'
    ELSE current_phase
END;

-- 更新 transfer_market_events 表中的 phase
UPDATE transfer_market_events
SET phase = CASE phase
    WHEN 'INITIALIZATION' THEN 'INTENTION_GENERATION'
    WHEN 'INTENTION_GENERATION' THEN 'INTENTION_GENERATION'
    WHEN 'STRATEGY_GENERATION' THEN 'STRATEGY_GENERATION'
    WHEN 'RENEWAL_PROCESSING' THEN 'RENEWAL_PROCESSING'
    WHEN 'DEPARTURE_ANNOUNCEMENT' THEN 'FREE_MARKET'
    WHEN 'INITIAL_BIDDING' THEN 'FREE_MARKET'
    WHEN 'NEGOTIATION_ROUNDS' THEN 'FREE_MARKET'
    WHEN 'LAST_CHANCE' THEN 'FREE_MARKET'
    WHEN 'TRANSFER_ROUNDS' THEN 'TRANSFER_ROUNDS'
    WHEN 'FINALIZATION' THEN 'COMPLETED'
    WHEN 'COMPLETED' THEN 'COMPLETED'
    ELSE phase
END;

-- 重置轮次计数（如果当前在自由市场阶段）
UPDATE transfer_market_states
SET current_round = 0
WHERE current_phase IN ('FREE_MARKET', 'TRANSFER_ROUNDS');

SELECT 'MarketPhase 迁移完成：11个阶段 -> 5个阶段' AS message;
