use super::DraftPlayerConfig;

pub(super) fn get_lec_draft_pool() -> Vec<DraftPlayerConfig> {
    vec![
        DraftPlayerConfig {
            game_id: "Axel",
            real_name: "阿克塞尔·杜邦",
            position: "Top",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Fenr",
            real_name: "列奥·费尔南德斯",
            position: "Jug",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Milo",
            real_name: "米洛·施密特",
            position: "Sup",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Kairo",
            real_name: "凯·约翰森",
            position: "Mid",
            ability: 65,
            potential: 68,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Theo",
            real_name: "西奥·罗西",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Erik",
            real_name: "埃里克·诺瓦克",
            position: "Jug",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Luca",
            real_name: "卢卡·莫雷蒂",
            position: "Mid",
            ability: 66,
            potential: 69,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Nyx",
            real_name: "诺亚·佩特罗夫",
            position: "Sup",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Hugo",
            real_name: "雨果·拉丰",
            position: "Top",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Felix",
            real_name: "菲利克斯·贝克",
            position: "Adc",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Arlo",
            real_name: "阿洛·伊万诺夫",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Elias",
            real_name: "伊莱亚斯·霍尔特",
            position: "Mid",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Maxx",
            real_name: "马克斯·勒克莱尔",
            position: "Top",
            ability: 65,
            potential: 68,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Oscar",
            real_name: "奥斯卡·桑切斯",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Liam",
            real_name: "利亚姆·穆勒",
            position: "Sup",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Remy",
            real_name: "雷米·杜兰",
            position: "Mid",
            ability: 67,
            potential: 69,
            stability: 55,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Jules",
            real_name: "朱尔斯·马丁",
            position: "Jug",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Finn",
            real_name: "芬恩·奥康奈尔",
            position: "Top",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 17,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Theon",
            real_name: "西昂·贝特朗",
            position: "Mid",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Nils",
            real_name: "尼尔斯·科瓦奇",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Emil",
            real_name: "埃米尔·拉森",
            position: "Sup",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Viktor",
            real_name: "维克托·索伦森",
            position: "Adc",
            ability: 66,
            potential: 69,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Anton",
            real_name: "安东·雷耶斯",
            position: "Top",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Bruno",
            real_name: "布鲁诺·加西亚",
            position: "Jug",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Casp",
            real_name: "卡斯佩尔·诺瓦克",
            position: "Sup",
            ability: 65,
            potential: 67,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Diego",
            real_name: "迭戈·罗西",
            position: "Adc",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Enzo",
            real_name: "恩佐·杜邦",
            position: "Top",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Gabe",
            real_name: "加布·彼得森",
            position: "Mid",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Huxley",
            real_name: "雨果·施密特",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Ivo",
            real_name: "伊沃·科瓦奇",
            position: "Sup",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Jayce",
            real_name: "杰·威廉姆斯",
            position: "Adc",
            ability: 67,
            potential: 69,
            stability: 55,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Kian",
            real_name: "基安·穆罕默德",
            position: "Top",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Lars",
            real_name: "拉斯·霍尔特",
            position: "Jug",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Matteo",
            real_name: "马泰奥·罗西",
            position: "Mid",
            ability: 66,
            potential: 68,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Nico",
            real_name: "尼科·贝克",
            position: "Sup",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Otto",
            real_name: "奥托·施密特",
            position: "Top",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Pablo",
            real_name: "巴勃罗·费尔南德斯",
            position: "Adc",
            ability: 65,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Quinn",
            real_name: "昆·李",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Rico",
            real_name: "里科·加西亚",
            position: "Sup",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Sami",
            real_name: "萨米·伊万诺夫",
            position: "Mid",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Tomm",
            real_name: "汤姆·约翰森",
            position: "Top",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Ugo",
            real_name: "于戈·杜兰",
            position: "Jug",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Valen",
            real_name: "瓦伦·莫雷蒂",
            position: "Adc",
            ability: 67,
            potential: 69,
            stability: 56,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Wesk",
            real_name: "韦斯·彼得森",
            position: "Sup",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Xavi",
            real_name: "哈维·罗西",
            position: "Top",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Yann",
            real_name: "扬·勒布朗",
            position: "Mid",
            ability: 65,
            potential: 68,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Zane",
            real_name: "泽恩·科瓦奇",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Alaric",
            real_name: "阿拉里克·穆勒",
            position: "Sup",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Bjorn",
            real_name: "比约恩·霍尔特",
            position: "Adc",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Cael",
            real_name: "凯厄斯·贝克",
            position: "Top",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
    ]
}
