use super::DraftPlayerConfig;

pub(super) fn get_lpl_draft_pool() -> Vec<DraftPlayerConfig> {
    vec![
        DraftPlayerConfig {
            game_id: "Anzo",
            real_name: "安森·林",
            position: "Top",
            ability: 64,
            potential: 67,
            stability: 53,
            age: 18,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Benx",
            real_name: "本·陈",
            position: "Jug",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Carl",
            real_name: "卡尔·王",
            position: "Sup",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Dean",
            real_name: "迪恩·李",
            position: "Mid",
            ability: 65,
            potential: 68,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Evan",
            real_name: "伊凡·张",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "FelixCN",
            real_name: "菲力·黄",
            position: "Top",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Gavn",
            real_name: "加文·周",
            position: "Jug",
            ability: 66,
            potential: 69,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Henr",
            real_name: "亨利·吴",
            position: "Sup",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Ivan",
            real_name: "伊万·郑",
            position: "Adc",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Jack",
            real_name: "杰克·徐",
            position: "Mid",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Kenz",
            real_name: "肯·杨",
            position: "Jug",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Leon",
            real_name: "利奥·郭",
            position: "Top",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "MarkCN",
            real_name: "马克·何",
            position: "Adc",
            ability: 67,
            potential: 69,
            stability: 55,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Nick",
            real_name: "尼克·谢",
            position: "Sup",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "OwenCN",
            real_name: "欧文·林",
            position: "Mid",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Paul",
            real_name: "保罗·陈",
            position: "Jug",
            ability: 65,
            potential: 67,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "QuinCN",
            real_name: "昆·王",
            position: "Sup",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Rayn",
            real_name: "雷·李",
            position: "Adc",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Samx",
            real_name: "山姆·张",
            position: "Mid",
            ability: 64,
            potential: 68,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Tomz",
            real_name: "汤姆·黄",
            position: "Top",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Urix",
            real_name: "尤里·周",
            position: "Jug",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Vicx",
            real_name: "维克·吴",
            position: "Sup",
            ability: 66,
            potential: 69,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Will",
            real_name: "威尔·郑",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Xylo",
            real_name: "赛恩·徐",
            position: "Mid",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Yanz",
            real_name: "彦·杨",
            position: "Top",
            ability: 67,
            potential: 69,
            stability: 56,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Zack",
            real_name: "扎克·林",
            position: "Jug",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Acex",
            real_name: "艾斯·陈",
            position: "Adc",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Boyz",
            real_name: "波·王",
            position: "Sup",
            ability: 65,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Cyra",
            real_name: "赛·李",
            position: "Mid",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Dexy",
            real_name: "德克斯·张",
            position: "Top",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Eliu",
            real_name: "伊莱·黄",
            position: "Jug",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Finx",
            real_name: "芬恩·周",
            position: "Sup",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Gusx",
            real_name: "格斯·吴",
            position: "Adc",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Hawx",
            real_name: "霍克·郑",
            position: "Mid",
            ability: 67,
            potential: 69,
            stability: 55,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Ianz",
            real_name: "伊恩·徐",
            position: "Top",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "JayxCN",
            real_name: "杰·杨",
            position: "Jug",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Kaiz",
            real_name: "凯·林",
            position: "Sup",
            ability: 66,
            potential: 68,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Lenx",
            real_name: "伦·陈",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Maxi",
            real_name: "麦克斯·王",
            position: "Mid",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Neox",
            real_name: "尼奥·李",
            position: "Jug",
            ability: 65,
            potential: 67,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Olix",
            real_name: "奥利·张",
            position: "Sup",
            ability: 62,
            potential: 64,
            stability: 51,
            age: 17,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Petz",
            real_name: "皮特·黄",
            position: "Adc",
            ability: 61,
            potential: 63,
            stability: 51,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Quix",
            real_name: "昆·周",
            position: "Mid",
            ability: 64,
            potential: 67,
            stability: 54,
            age: 19,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Royx",
            real_name: "罗伊·吴",
            position: "Top",
            ability: 64,
            potential: 66,
            stability: 53,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Sidz",
            real_name: "西德·郑",
            position: "Jug",
            ability: 60,
            potential: 62,
            stability: 50,
            age: 16,
            tag: "Ordinary",
        },
        DraftPlayerConfig {
            game_id: "Timx",
            real_name: "蒂姆·徐",
            position: "Sup",
            ability: 67,
            potential: 69,
            stability: 55,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Uzix",
            real_name: "乌兹·杨",
            position: "Adc",
            ability: 62,
            potential: 64,
            stability: 52,
            age: 18,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Vanx",
            real_name: "范·林",
            position: "Mid",
            ability: 63,
            potential: 65,
            stability: 53,
            age: 19,
            tag: "Normal",
        },
        DraftPlayerConfig {
            game_id: "Wesx",
            real_name: "韦斯·陈",
            position: "Jug",
            ability: 66,
            potential: 69,
            stability: 54,
            age: 20,
            tag: "Genius",
        },
        DraftPlayerConfig {
            game_id: "Tenx",
            real_name: "天·张",
            position: "Top",
            ability: 67,
            potential: 69,
            stability: 56,
            age: 19,
            tag: "Genius",
        },
    ]
}
